# Generated by Django 4.1.3 on 2022-12-31 16:16

from django.db import migrations, models
import user_dashboard_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
