# Generated by Django 4.1.3 on 2022-12-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
