# Generated by Django 4.1.3 on 2023-01-01 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0004_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='written_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages_written_by', to='user_dashboard_app.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='written_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages_written_to', to='user_dashboard_app.user'),
        ),
    ]
