# Generated by Django 4.1.3 on 2023-01-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0005_remove_message_user_message_written_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
